'use client';

import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import { toast } from 'sonner';
import api from '@/lib/api';
import { Printer, Loader2, ChevronDown, MessageSquare, Target, AlertTriangle } from 'lucide-react';

export default function InterviewQuestionsPage() {
  const { id } = useParams<{ id: string }>();
  const [role, setRole] = useState<any>(null);
  const [candidates, setCandidates] = useState<any[]>([]);
  const [selectedCandidate, setSelectedCandidate] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadQuestions();
  }, [id]);

  const loadQuestions = async () => {
    try {
      const { role: r, candidates: c } = await api.getQuestions(id);
      setRole(r);
      setCandidates(c);
      if (c.length > 0) setSelectedCandidate(c[0]._id);
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      setLoading(false);
    }
  };

  const selected = candidates.find((c) => c._id === selectedCandidate);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="w-6 h-6 animate-spin" style={{ color: 'var(--accent-primary)' }} />
      </div>
    );
  }

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between mb-6 no-print">
        <div>
          <h1 className="text-2xl font-bold">Interview Questions</h1>
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{role?.title}</p>
        </div>
        <div className="flex items-center gap-3">
          {/* Candidate Selector */}
          <select
            className="input-field w-auto pr-8"
            value={selectedCandidate}
            onChange={(e) => setSelectedCandidate(e.target.value)}
          >
            {candidates.map((c) => (
              <option key={c._id} value={c._id}>{c.name}</option>
            ))}
          </select>

          <button className="btn-primary flex items-center gap-2" onClick={() => window.print()}>
            <Printer className="w-4 h-4" />
            Print
          </button>
        </div>
      </div>

      {/* Print Header (visible only in print) */}
      <div className="print-only mb-8">
        <h1 className="text-xl font-bold">{role?.title} — Interview Questions</h1>
        <p className="text-sm">Candidate: {selected?.name}</p>
        <p className="text-xs" style={{ color: '#666' }}>Generated by TalentScore</p>
      </div>

      {candidates.length === 0 ? (
        <div className="card-glow p-12 text-center">
          <MessageSquare className="w-12 h-12 mx-auto mb-4" style={{ color: 'var(--text-muted)' }} />
          <h3 className="text-lg font-semibold mb-2">No questions generated yet</h3>
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
            Go to the candidates page and click "Generate Questions" after uploading resumes.
          </p>
        </div>
      ) : selected?.questions ? (
        <div className="space-y-6">
          {/* Standard Questions */}
          {selected.questions.standard?.length > 0 && (
            <div className="card p-6">
              <h2 className="text-sm font-semibold mb-4 flex items-center gap-2" style={{ color: 'var(--accent-primary)' }}>
                <MessageSquare className="w-4 h-4" />
                STANDARD QUESTIONS
                <span className="text-xs font-normal" style={{ color: 'var(--text-muted)' }}>(same for all candidates)</span>
              </h2>
              <div className="space-y-4">
                {selected.questions.standard.map((q: any, i: number) => (
                  <div key={i} className="p-4 rounded-xl" style={{ background: 'var(--bg-secondary)' }}>
                    <p className="font-medium text-sm mb-2">
                      <span style={{ color: 'var(--accent-primary)' }}>{i + 1}.</span> {q.question}
                    </p>
                    {q.category && (
                      <span className="badge badge-info text-xs mb-2">Category: {q.category}</span>
                    )}
                    {q.followUp && (
                      <p className="text-xs mt-2 pl-4 border-l-2" style={{ color: 'var(--text-muted)', borderColor: 'var(--border-primary)' }}>
                        <strong>If vague:</strong> {q.followUp}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Candidate-Specific Questions */}
          {selected.questions.candidateSpecific?.length > 0 && (
            <div className="card p-6">
              <h2 className="text-sm font-semibold mb-4 flex items-center gap-2" style={{ color: 'var(--warning)' }}>
                <Target className="w-4 h-4" />
                CANDIDATE-SPECIFIC
                <span className="text-xs font-normal" style={{ color: 'var(--text-muted)' }}>(for {selected.name})</span>
              </h2>
              <div className="space-y-4">
                {selected.questions.candidateSpecific.map((q: any, i: number) => (
                  <div key={i} className="p-4 rounded-xl" style={{ background: 'var(--bg-secondary)' }}>
                    <p className="font-medium text-sm mb-2">
                      <span style={{ color: 'var(--warning)' }}>{i + 1}.</span> {q.question}
                    </p>
                    {q.rationale && (
                      <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                        <strong>Why:</strong> {q.rationale}
                      </p>
                    )}
                    {q.probing && (
                      <p className="text-xs mt-1 pl-4 border-l-2" style={{ color: 'var(--text-muted)', borderColor: 'var(--border-primary)' }}>
                        <strong>Probe:</strong> {q.probing}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Behavioral / Risk Questions */}
          {selected.questions.behavioral?.length > 0 && (
            <div className="card p-6">
              <h2 className="text-sm font-semibold mb-4 flex items-center gap-2" style={{ color: 'var(--danger)' }}>
                <AlertTriangle className="w-4 h-4" />
                BEHAVIORAL / RISK QUESTIONS
              </h2>
              <div className="space-y-4">
                {selected.questions.behavioral.map((q: any, i: number) => (
                  <div key={i} className="p-4 rounded-xl" style={{ background: 'var(--bg-secondary)' }}>
                    <p className="font-medium text-sm mb-2">
                      <span style={{ color: 'var(--danger)' }}>{i + 1}.</span> {q.question}
                    </p>
                    {q.targetBehavior && (
                      <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                        <strong>Detecting:</strong> {q.targetBehavior}
                      </p>
                    )}
                    {q.redFlagAnswers?.length > 0 && (
                      <div className="mt-2">
                        <p className="text-xs font-medium" style={{ color: 'var(--danger)' }}>🚩 Red Flag Answers:</p>
                        <ul className="text-xs mt-1 space-y-0.5" style={{ color: 'var(--text-muted)' }}>
                          {q.redFlagAnswers.map((r: string, j: number) => (
                            <li key={j}>• {r}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="card-glow p-12 text-center">
          <p style={{ color: 'var(--text-muted)' }}>No questions generated for this candidate yet.</p>
        </div>
      )}
    </div>
  );
}
